name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: flutter test --coverage
      - run: bash -lc "genhtml coverage/lcov.info -o coverage/html" || true
      # Optional: golden tests need this
      - name: Upload failed goldens
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: golden-failures
          path: test/**/failures/*.png
